abstract final class AppRoutes {
  static const splash = '/';
  static const onboarding = '/onboarding';
  static const authStart = '/auth/start';
  static const signupTerms = '/signup/terms';
  static const signupVerify = '/signup/verify';
  static const signupProfile = '/signup/profile';
  static const signupComplete = '/signup/complete';
  static const home = '/home';
  static const myInfo = '/my/info';
  static const myWithdraw = '/my/withdraw';
  static const myPetList = '/my/pets';
  static const myPetDetail = '/my/pets/:myPetId';
  static const myPetEdit = '/my/pets/:myPetId/edit';
  static const myPetAdd = '/my/pets/add';
  static const myPetDetailForm = '/my/pets/add/details';
  static const myPetBreedSelect = '/my/pets/add/breed-select';
  static const myPetStoryForm = '/my/pets/add/story';
  static const myPetHealthForm = '/my/pets/add/health';
  static const myPetAddComplete = '/my/pets/add/complete';
  static const addressWebView = '/webview/address';
  static const customerCenter = '/my/customer-center';
  static const notificationCenter = '/notification-center';
}

abstract final class AppRouteNames {
  static const splash = 'splash';
  static const onboarding = 'onboarding';
  static const authStart = 'authStart';
  static const signupTerms = 'signupTerms';
  static const signupVerify = 'signupVerify';
  static const signupProfile = 'signupProfile';
  static const signupComplete = 'signupComplete';
  static const home = 'home';
  static const myInfo = 'myInfo';
  static const myWithdraw = 'myWithdraw';
  static const myPetList = 'myPetList';
  static const myPetDetail = 'myPetDetail';
  static const myPetEdit = 'myPetEdit';
  static const myPetAdd = 'myPetAdd';
  static const myPetDetailForm = 'myPetDetailForm';
  static const myPetBreedSelect = 'myPetBreedSelect';
  static const myPetStoryForm = 'myPetStoryForm';
  static const myPetHealthForm = 'myPetHealthForm';
  static const myPetAddComplete = 'myPetAddComplete';
  static const addressWebView = 'addressWebView';
  static const customerCenter = 'customerCenter';
  static const notificationCenter = 'notificationCenter';
}
